name: Lint, Test, and Build Frontend
# We should update this to also lint and test the backend

on:
  pull_request:
    paths:
      - "frontend/**"

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    concurrency:
      cancel-in-progress: true
      group: ${{ github.head_ref }}
    steps:
      - name: Checkout repo.
        uses: actions/checkout@v2
      - name: Get yarn cache directory
        id: yarn-cache-dir-path
        run: echo "::set-output name=YARN_CACHE::$(yarn cache dir)"
      - name: Cache node modules
        id: lerna-yarn-cache
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: |
            ${{ steps.yarn-cache-dir-path.outputs.YARN_CACHE }}
            **/node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: Install dependencies if needed.
        if: steps.lerna-yarn-cache.outputs.cache-hit != 'true'
        run: cd frontend && yarn install --ignore-platform --ignore-engines --ignore-scripts --frozen-lockfile
      - name: Lint Website
        run: cd frontend && yarn lint
      - name: Test Website
        run: cd frontend && yarn test
      - name: Build Website
        run: cd frontend && yarn build